-- SCRIPT DE CRIÇÃO DAS TABELAS DO BANCO

-- TABELAS

CREATE TABLE CB_ENDERECO(
	IDENDERECO INT IDENTITY(1,1),
	DESCRICAO VARCHAR(50) NOT NULL,
	LOGRADOURO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL
)
GO

-- CHAVES PRIMÁRIAS

ALTER TABLE CB_ENDERECO
ADD CONSTRAINT PK_IDENDERECO PRIMARY KEY
CLUSTERED (IDENDERECO)
GO