-- SCRIPT DE CRIÇÃO DAS TABELAS DO BANCO

-- TABELAS

CREATE TABLE CB_PESSOA(
	IDPESSOA INT IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(12) UNIQUE NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M', 'F')),
	ID_ENDERECO INT NOT NULL,
)
GO

CREATE TABLE CB_ENDERECO(
	IDENDERECO INT IDENTITY(1,1),
	DESCRICAO VARCHAR(50) NOT NULL,
	LOGRADOURO VARCHAR(20) NOT NULL,
	BAIRRO VARCHAR(20) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL
)
GO

-- CHAVES PRIMÁRIAS

ALTER TABLE CB_PESSOA 
ADD CONSTRAINT PK_IDPESSOA PRIMARY KEY 
CLUSTERED (IDPESSOA)
GO

ALTER TABLE CB_ENDERECO
ADD CONSTRAINT PK_IDENDERECO PRIMARY KEY
CLUSTERED (IDENDERECO)
GO

-- CHAVE ESTRANGEIRA

ALTER TABLE CB_PESSOA 
ADD CONSTRAINT FK_PESSOA_ENDERECO FOREIGN KEY (ID_ENDERECO) 
REFERENCES CB_ENDERECO (IDENDERECO)
GO